name: gatuno

services:
  scraper-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure:3
    # Usando Docker Compose Watch ao invés de Bind Mounts para melhor performance no Mac/Windows
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git/
            - node_modules/
            - tmp/
    env_file:
      - .env
    ports:
      - "6060:6060"
    depends_on:
      flaresolverr:
        condition: service_healthy
      browserless:
        condition: service_healthy
    networks:
      - gatuno-net

  browserless:
    image: ghcr.io/browserless/chromium:v2.55.3
    ports:
      - "3002:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=300000
      - ENABLE_DEBUGGER=true
      - ENABLE_CORS=true
    networks:
      - gatuno-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
    container_name: scraping-flaresolverr
    environment:
      - LOG_LEVEL=info
    networks:
      - gatuno-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  gatuno-net:
    external: true
    name: gatuno_gatuno-net
